// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_resource_ap_fixed_9_4_0_0_0_ap_fixed_9_4_5_3_0_config15_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        ap_return
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
output  [8:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[8:0] ap_return;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln42_fu_506_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] w15_V_address0;
reg    w15_V_ce0;
wire  signed [7:0] w15_V_q0;
wire   [3:0] w15_V_address1;
reg    w15_V_ce1;
wire  signed [7:0] w15_V_q1;
reg   [0:0] do_init_reg_157;
reg   [2:0] in_index9_reg_173;
reg   [7:0] p_read12_rewind_reg_188;
reg   [7:0] p_read113_rewind_reg_202;
reg   [7:0] p_read214_rewind_reg_216;
reg   [7:0] p_read315_rewind_reg_230;
reg   [7:0] p_read416_rewind_reg_244;
reg   [7:0] p_read517_rewind_reg_258;
reg   [7:0] p_read618_rewind_reg_272;
reg   [7:0] p_read719_rewind_reg_286;
reg   [7:0] p_read820_rewind_reg_300;
reg   [7:0] p_read921_rewind_reg_314;
reg   [8:0] res_010_reg_328;
reg   [0:0] ap_phi_mux_do_init_phi_fu_161_p6;
wire   [2:0] in_index_fu_500_p2;
reg   [2:0] in_index_reg_668;
reg   [0:0] icmp_ln42_reg_673;
wire   [8:0] add_ln813_1_fu_598_p2;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
reg   [2:0] ap_phi_mux_in_index9_phi_fu_177_p6;
reg   [7:0] ap_phi_mux_p_read12_phi_phi_fu_346_p4;
reg   [7:0] ap_phi_mux_p_read113_phi_phi_fu_358_p4;
reg   [7:0] ap_phi_mux_p_read214_phi_phi_fu_370_p4;
reg   [7:0] ap_phi_mux_p_read315_phi_phi_fu_382_p4;
reg   [7:0] ap_phi_mux_p_read416_phi_phi_fu_394_p4;
reg   [7:0] ap_phi_mux_p_read517_phi_phi_fu_406_p4;
reg   [7:0] ap_phi_mux_p_read618_phi_phi_fu_418_p4;
reg   [7:0] ap_phi_mux_p_read719_phi_phi_fu_430_p4;
reg   [7:0] ap_phi_mux_p_read820_phi_phi_fu_442_p4;
reg   [7:0] ap_phi_mux_p_read921_phi_phi_fu_454_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read12_phi_reg_342;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read12_phi_reg_342;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read113_phi_reg_354;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read113_phi_reg_354;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read214_phi_reg_366;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read214_phi_reg_366;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read315_phi_reg_378;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read315_phi_reg_378;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read416_phi_reg_390;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read416_phi_reg_390;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read517_phi_reg_402;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read517_phi_reg_402;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read618_phi_reg_414;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read618_phi_reg_414;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read719_phi_reg_426;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read719_phi_reg_426;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read820_phi_reg_438;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read820_phi_reg_438;
wire   [7:0] ap_phi_reg_pp0_iter0_p_read921_phi_reg_450;
reg   [7:0] ap_phi_reg_pp0_iter1_p_read921_phi_reg_450;
wire   [63:0] zext_ln42_fu_462_p1;
wire   [63:0] p_cast3_fu_495_p1;
wire   [3:0] tmp_1_fu_467_p3;
wire   [4:0] p_cast_fu_475_p1;
wire   [4:0] empty_34_fu_479_p2;
wire   [3:0] tmp_2_fu_485_p4;
wire   [7:0] tmp_fu_512_p7;
wire   [7:0] mul_ln1270_fu_536_p1;
wire   [14:0] mul_ln1270_fu_536_p2;
wire   [7:0] tmp_s_fu_552_p7;
wire   [7:0] mul_ln1270_1_fu_576_p1;
wire   [14:0] mul_ln1270_1_fu_576_p2;
wire   [8:0] trunc_ln818_1_fu_582_p4;
wire   [8:0] trunc_ln_fu_542_p4;
wire   [8:0] add_ln813_fu_592_p2;
reg   [8:0] ap_return_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [14:0] mul_ln1270_1_fu_576_p10;
wire   [14:0] mul_ln1270_fu_536_p10;
reg    ap_condition_165;
reg    ap_condition_42;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_return_preg = 9'd0;
end

myproject_dense_resource_ap_fixed_9_4_0_0_0_ap_fixed_9_4_5_3_0_config15_s_w15_V_ROM_AUTdEe #(
    .DataWidth( 8 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
w15_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w15_V_address0),
    .ce0(w15_V_ce0),
    .q0(w15_V_q0),
    .address1(w15_V_address1),
    .ce1(w15_V_ce1),
    .q1(w15_V_q1)
);

myproject_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U1873(
    .din0(ap_phi_mux_p_read12_phi_phi_fu_346_p4),
    .din1(ap_phi_mux_p_read113_phi_phi_fu_358_p4),
    .din2(ap_phi_mux_p_read214_phi_phi_fu_370_p4),
    .din3(ap_phi_mux_p_read315_phi_phi_fu_382_p4),
    .din4(ap_phi_mux_p_read416_phi_phi_fu_394_p4),
    .din5(in_index9_reg_173),
    .dout(tmp_fu_512_p7)
);

myproject_mul_8s_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8s_8ns_15_1_1_U1874(
    .din0(w15_V_q1),
    .din1(mul_ln1270_fu_536_p1),
    .dout(mul_ln1270_fu_536_p2)
);

myproject_mux_53_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_53_8_1_1_U1875(
    .din0(ap_phi_mux_p_read517_phi_phi_fu_406_p4),
    .din1(ap_phi_mux_p_read618_phi_phi_fu_418_p4),
    .din2(ap_phi_mux_p_read719_phi_phi_fu_430_p4),
    .din3(ap_phi_mux_p_read820_phi_phi_fu_442_p4),
    .din4(ap_phi_mux_p_read921_phi_phi_fu_454_p4),
    .din5(in_index9_reg_173),
    .dout(tmp_s_fu_552_p7)
);

myproject_mul_8s_8ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 15 ))
mul_8s_8ns_15_1_1_U1876(
    .din0(w15_V_q0),
    .din1(mul_ln1270_1_fu_576_p1),
    .dout(mul_ln1270_1_fu_576_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 9'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1))) begin
            ap_return_preg <= add_ln813_1_fu_598_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read113_phi_reg_354 <= p_read1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read113_phi_reg_354 <= ap_phi_reg_pp0_iter0_p_read113_phi_reg_354;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read12_phi_reg_342 <= p_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read12_phi_reg_342 <= ap_phi_reg_pp0_iter0_p_read12_phi_reg_342;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read214_phi_reg_366 <= p_read2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read214_phi_reg_366 <= ap_phi_reg_pp0_iter0_p_read214_phi_reg_366;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read315_phi_reg_378 <= p_read3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read315_phi_reg_378 <= ap_phi_reg_pp0_iter0_p_read315_phi_reg_378;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read416_phi_reg_390 <= p_read4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read416_phi_reg_390 <= ap_phi_reg_pp0_iter0_p_read416_phi_reg_390;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read517_phi_reg_402 <= p_read5;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read517_phi_reg_402 <= ap_phi_reg_pp0_iter0_p_read517_phi_reg_402;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read618_phi_reg_414 <= p_read6;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read618_phi_reg_414 <= ap_phi_reg_pp0_iter0_p_read618_phi_reg_414;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read719_phi_reg_426 <= p_read7;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read719_phi_reg_426 <= ap_phi_reg_pp0_iter0_p_read719_phi_reg_426;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read820_phi_reg_438 <= p_read8;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read820_phi_reg_438 <= ap_phi_reg_pp0_iter0_p_read820_phi_reg_438;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_42)) begin
        if ((ap_phi_mux_do_init_phi_fu_161_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_read921_phi_reg_450 <= p_read9;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_read921_phi_reg_450 <= ap_phi_reg_pp0_iter0_p_read921_phi_reg_450;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd0))) begin
        do_init_reg_157 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_157 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd0))) begin
        in_index9_reg_173 <= in_index_reg_668;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index9_reg_173 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd0))) begin
        res_010_reg_328 <= add_ln813_1_fu_598_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1)) | (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_010_reg_328 <= 9'd6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln42_reg_673 <= icmp_ln42_fu_506_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_668 <= in_index_fu_500_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd0))) begin
        p_read113_rewind_reg_202 <= ap_phi_mux_p_read113_phi_phi_fu_358_p4;
        p_read12_rewind_reg_188 <= ap_phi_mux_p_read12_phi_phi_fu_346_p4;
        p_read214_rewind_reg_216 <= ap_phi_mux_p_read214_phi_phi_fu_370_p4;
        p_read315_rewind_reg_230 <= ap_phi_mux_p_read315_phi_phi_fu_382_p4;
        p_read416_rewind_reg_244 <= ap_phi_mux_p_read416_phi_phi_fu_394_p4;
        p_read517_rewind_reg_258 <= ap_phi_mux_p_read517_phi_phi_fu_406_p4;
        p_read618_rewind_reg_272 <= ap_phi_mux_p_read618_phi_phi_fu_418_p4;
        p_read719_rewind_reg_286 <= ap_phi_mux_p_read719_phi_phi_fu_430_p4;
        p_read820_rewind_reg_300 <= ap_phi_mux_p_read820_phi_phi_fu_442_p4;
        p_read921_rewind_reg_314 <= ap_phi_mux_p_read921_phi_phi_fu_454_p4;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_165)) begin
        if ((icmp_ln42_reg_673 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_161_p6 = 1'd1;
        end else if ((icmp_ln42_reg_673 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_161_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_161_p6 = do_init_reg_157;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_161_p6 = do_init_reg_157;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_165)) begin
        if ((icmp_ln42_reg_673 == 1'd1)) begin
            ap_phi_mux_in_index9_phi_fu_177_p6 = 3'd0;
        end else if ((icmp_ln42_reg_673 == 1'd0)) begin
            ap_phi_mux_in_index9_phi_fu_177_p6 = in_index_reg_668;
        end else begin
            ap_phi_mux_in_index9_phi_fu_177_p6 = in_index9_reg_173;
        end
    end else begin
        ap_phi_mux_in_index9_phi_fu_177_p6 = in_index9_reg_173;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read113_phi_phi_fu_358_p4 = p_read113_rewind_reg_202;
    end else begin
        ap_phi_mux_p_read113_phi_phi_fu_358_p4 = ap_phi_reg_pp0_iter1_p_read113_phi_reg_354;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read12_phi_phi_fu_346_p4 = p_read12_rewind_reg_188;
    end else begin
        ap_phi_mux_p_read12_phi_phi_fu_346_p4 = ap_phi_reg_pp0_iter1_p_read12_phi_reg_342;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read214_phi_phi_fu_370_p4 = p_read214_rewind_reg_216;
    end else begin
        ap_phi_mux_p_read214_phi_phi_fu_370_p4 = ap_phi_reg_pp0_iter1_p_read214_phi_reg_366;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read315_phi_phi_fu_382_p4 = p_read315_rewind_reg_230;
    end else begin
        ap_phi_mux_p_read315_phi_phi_fu_382_p4 = ap_phi_reg_pp0_iter1_p_read315_phi_reg_378;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read416_phi_phi_fu_394_p4 = p_read416_rewind_reg_244;
    end else begin
        ap_phi_mux_p_read416_phi_phi_fu_394_p4 = ap_phi_reg_pp0_iter1_p_read416_phi_reg_390;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read517_phi_phi_fu_406_p4 = p_read517_rewind_reg_258;
    end else begin
        ap_phi_mux_p_read517_phi_phi_fu_406_p4 = ap_phi_reg_pp0_iter1_p_read517_phi_reg_402;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read618_phi_phi_fu_418_p4 = p_read618_rewind_reg_272;
    end else begin
        ap_phi_mux_p_read618_phi_phi_fu_418_p4 = ap_phi_reg_pp0_iter1_p_read618_phi_reg_414;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read719_phi_phi_fu_430_p4 = p_read719_rewind_reg_286;
    end else begin
        ap_phi_mux_p_read719_phi_phi_fu_430_p4 = ap_phi_reg_pp0_iter1_p_read719_phi_reg_426;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read820_phi_phi_fu_442_p4 = p_read820_rewind_reg_300;
    end else begin
        ap_phi_mux_p_read820_phi_phi_fu_442_p4 = ap_phi_reg_pp0_iter1_p_read820_phi_reg_438;
    end
end

always @ (*) begin
    if ((do_init_reg_157 == 1'd0)) begin
        ap_phi_mux_p_read921_phi_phi_fu_454_p4 = p_read921_rewind_reg_314;
    end else begin
        ap_phi_mux_p_read921_phi_phi_fu_454_p4 = ap_phi_reg_pp0_iter1_p_read921_phi_reg_450;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln42_fu_506_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln42_reg_673 == 1'd1))) begin
        ap_return = add_ln813_1_fu_598_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w15_V_ce0 = 1'b1;
    end else begin
        w15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w15_V_ce1 = 1'b1;
    end else begin
        w15_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln813_1_fu_598_p2 = (res_010_reg_328 + add_ln813_fu_592_p2);

assign add_ln813_fu_592_p2 = (trunc_ln818_1_fu_582_p4 + trunc_ln_fu_542_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_165 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_42 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_p_read113_phi_reg_354 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read12_phi_reg_342 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read214_phi_reg_366 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read315_phi_reg_378 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read416_phi_reg_390 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read517_phi_reg_402 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read618_phi_reg_414 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read719_phi_reg_426 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read820_phi_reg_438 = 'bx;

assign ap_phi_reg_pp0_iter0_p_read921_phi_reg_450 = 'bx;

assign empty_34_fu_479_p2 = (p_cast_fu_475_p1 + 5'd10);

assign icmp_ln42_fu_506_p2 = ((ap_phi_mux_in_index9_phi_fu_177_p6 == 3'd4) ? 1'b1 : 1'b0);

assign in_index_fu_500_p2 = (ap_phi_mux_in_index9_phi_fu_177_p6 + 3'd1);

assign mul_ln1270_1_fu_576_p1 = mul_ln1270_1_fu_576_p10;

assign mul_ln1270_1_fu_576_p10 = tmp_s_fu_552_p7;

assign mul_ln1270_fu_536_p1 = mul_ln1270_fu_536_p10;

assign mul_ln1270_fu_536_p10 = tmp_fu_512_p7;

assign p_cast3_fu_495_p1 = tmp_2_fu_485_p4;

assign p_cast_fu_475_p1 = tmp_1_fu_467_p3;

assign tmp_1_fu_467_p3 = {{ap_phi_mux_in_index9_phi_fu_177_p6}, {1'd0}};

assign tmp_2_fu_485_p4 = {{empty_34_fu_479_p2[4:1]}};

assign trunc_ln818_1_fu_582_p4 = {{mul_ln1270_1_fu_576_p2[14:6]}};

assign trunc_ln_fu_542_p4 = {{mul_ln1270_fu_536_p2[14:6]}};

assign w15_V_address0 = p_cast3_fu_495_p1;

assign w15_V_address1 = zext_ln42_fu_462_p1;

assign zext_ln42_fu_462_p1 = ap_phi_mux_in_index9_phi_fu_177_p6;

endmodule //myproject_dense_resource_ap_fixed_9_4_0_0_0_ap_fixed_9_4_5_3_0_config15_s
