-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_linear_ap_fixed_9_3_5_3_0_ap_fixed_16_6_0_0_0_linear_config13_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (8 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (8 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (12 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (12 downto 0) );
end;


architecture behav of myproject_linear_ap_fixed_9_3_5_3_0_ap_fixed_16_6_0_0_0_linear_config13_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal shl_ln_fu_96_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_1_fu_104_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_2_fu_112_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_3_fu_120_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_4_fu_128_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_5_fu_136_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_6_fu_144_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_7_fu_152_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_8_fu_160_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln838_9_fu_168_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_8_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_return_9_preg : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg(4) <= '0';
                ap_return_0_preg(5) <= '0';
                ap_return_0_preg(6) <= '0';
                ap_return_0_preg(7) <= '0';
                ap_return_0_preg(8) <= '0';
                ap_return_0_preg(9) <= '0';
                ap_return_0_preg(10) <= '0';
                ap_return_0_preg(11) <= '0';
                ap_return_0_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_0_preg(12 downto 4) <= shl_ln_fu_96_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg(4) <= '0';
                ap_return_1_preg(5) <= '0';
                ap_return_1_preg(6) <= '0';
                ap_return_1_preg(7) <= '0';
                ap_return_1_preg(8) <= '0';
                ap_return_1_preg(9) <= '0';
                ap_return_1_preg(10) <= '0';
                ap_return_1_preg(11) <= '0';
                ap_return_1_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_1_preg(12 downto 4) <= shl_ln838_1_fu_104_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg(4) <= '0';
                ap_return_2_preg(5) <= '0';
                ap_return_2_preg(6) <= '0';
                ap_return_2_preg(7) <= '0';
                ap_return_2_preg(8) <= '0';
                ap_return_2_preg(9) <= '0';
                ap_return_2_preg(10) <= '0';
                ap_return_2_preg(11) <= '0';
                ap_return_2_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_2_preg(12 downto 4) <= shl_ln838_2_fu_112_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg(4) <= '0';
                ap_return_3_preg(5) <= '0';
                ap_return_3_preg(6) <= '0';
                ap_return_3_preg(7) <= '0';
                ap_return_3_preg(8) <= '0';
                ap_return_3_preg(9) <= '0';
                ap_return_3_preg(10) <= '0';
                ap_return_3_preg(11) <= '0';
                ap_return_3_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_3_preg(12 downto 4) <= shl_ln838_3_fu_120_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg(4) <= '0';
                ap_return_4_preg(5) <= '0';
                ap_return_4_preg(6) <= '0';
                ap_return_4_preg(7) <= '0';
                ap_return_4_preg(8) <= '0';
                ap_return_4_preg(9) <= '0';
                ap_return_4_preg(10) <= '0';
                ap_return_4_preg(11) <= '0';
                ap_return_4_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_4_preg(12 downto 4) <= shl_ln838_4_fu_128_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg(4) <= '0';
                ap_return_5_preg(5) <= '0';
                ap_return_5_preg(6) <= '0';
                ap_return_5_preg(7) <= '0';
                ap_return_5_preg(8) <= '0';
                ap_return_5_preg(9) <= '0';
                ap_return_5_preg(10) <= '0';
                ap_return_5_preg(11) <= '0';
                ap_return_5_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_5_preg(12 downto 4) <= shl_ln838_5_fu_136_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg(4) <= '0';
                ap_return_6_preg(5) <= '0';
                ap_return_6_preg(6) <= '0';
                ap_return_6_preg(7) <= '0';
                ap_return_6_preg(8) <= '0';
                ap_return_6_preg(9) <= '0';
                ap_return_6_preg(10) <= '0';
                ap_return_6_preg(11) <= '0';
                ap_return_6_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_6_preg(12 downto 4) <= shl_ln838_6_fu_144_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg(4) <= '0';
                ap_return_7_preg(5) <= '0';
                ap_return_7_preg(6) <= '0';
                ap_return_7_preg(7) <= '0';
                ap_return_7_preg(8) <= '0';
                ap_return_7_preg(9) <= '0';
                ap_return_7_preg(10) <= '0';
                ap_return_7_preg(11) <= '0';
                ap_return_7_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_7_preg(12 downto 4) <= shl_ln838_7_fu_152_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_8_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_8_preg(4) <= '0';
                ap_return_8_preg(5) <= '0';
                ap_return_8_preg(6) <= '0';
                ap_return_8_preg(7) <= '0';
                ap_return_8_preg(8) <= '0';
                ap_return_8_preg(9) <= '0';
                ap_return_8_preg(10) <= '0';
                ap_return_8_preg(11) <= '0';
                ap_return_8_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_8_preg(12 downto 4) <= shl_ln838_8_fu_160_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;


    ap_return_9_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_9_preg(4) <= '0';
                ap_return_9_preg(5) <= '0';
                ap_return_9_preg(6) <= '0';
                ap_return_9_preg(7) <= '0';
                ap_return_9_preg(8) <= '0';
                ap_return_9_preg(9) <= '0';
                ap_return_9_preg(10) <= '0';
                ap_return_9_preg(11) <= '0';
                ap_return_9_preg(12) <= '0';
            else
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                                        ap_return_9_preg(12 downto 4) <= shl_ln838_9_fu_168_p3(12 downto 4);
                end if; 
            end if;
        end if;
    end process;

    ap_return_0_preg(3 downto 0) <= "0000";
    ap_return_1_preg(3 downto 0) <= "0000";
    ap_return_2_preg(3 downto 0) <= "0000";
    ap_return_3_preg(3 downto 0) <= "0000";
    ap_return_4_preg(3 downto 0) <= "0000";
    ap_return_5_preg(3 downto 0) <= "0000";
    ap_return_6_preg(3 downto 0) <= "0000";
    ap_return_7_preg(3 downto 0) <= "0000";
    ap_return_8_preg(3 downto 0) <= "0000";
    ap_return_9_preg(3 downto 0) <= "0000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln_fu_96_p3, ap_return_0_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= shl_ln_fu_96_p3;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_1_fu_104_p3, ap_return_1_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= shl_ln838_1_fu_104_p3;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_2_fu_112_p3, ap_return_2_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_2 <= shl_ln838_2_fu_112_p3;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_3_fu_120_p3, ap_return_3_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_3 <= shl_ln838_3_fu_120_p3;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_4_fu_128_p3, ap_return_4_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_4 <= shl_ln838_4_fu_128_p3;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_5_fu_136_p3, ap_return_5_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_5 <= shl_ln838_5_fu_136_p3;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_6_fu_144_p3, ap_return_6_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_6 <= shl_ln838_6_fu_144_p3;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_7_fu_152_p3, ap_return_7_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_7 <= shl_ln838_7_fu_152_p3;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_return_8_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_8_fu_160_p3, ap_return_8_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_8 <= shl_ln838_8_fu_160_p3;
        else 
            ap_return_8 <= ap_return_8_preg;
        end if; 
    end process;


    ap_return_9_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, shl_ln838_9_fu_168_p3, ap_return_9_preg)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_9 <= shl_ln838_9_fu_168_p3;
        else 
            ap_return_9 <= ap_return_9_preg;
        end if; 
    end process;

    shl_ln838_1_fu_104_p3 <= (p_read1 & ap_const_lv4_0);
    shl_ln838_2_fu_112_p3 <= (p_read2 & ap_const_lv4_0);
    shl_ln838_3_fu_120_p3 <= (p_read3 & ap_const_lv4_0);
    shl_ln838_4_fu_128_p3 <= (p_read4 & ap_const_lv4_0);
    shl_ln838_5_fu_136_p3 <= (p_read5 & ap_const_lv4_0);
    shl_ln838_6_fu_144_p3 <= (p_read6 & ap_const_lv4_0);
    shl_ln838_7_fu_152_p3 <= (p_read7 & ap_const_lv4_0);
    shl_ln838_8_fu_160_p3 <= (p_read8 & ap_const_lv4_0);
    shl_ln838_9_fu_168_p3 <= (p_read9 & ap_const_lv4_0);
    shl_ln_fu_96_p3 <= (p_read & ap_const_lv4_0);
end behav;
