-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config18_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read12 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read15 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read18 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read21 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read22 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read23 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read24 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read25 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read26 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read27 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read28 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read29 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read30 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read31 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read32 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read33 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read34 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read35 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read36 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read37 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read38 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read39 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read40 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read41 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read42 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read43 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read44 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read45 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read46 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read47 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read48 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read49 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read50 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read51 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read52 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read53 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read54 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read55 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read56 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read57 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read58 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read59 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read60 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read61 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read62 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read63 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read64 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read65 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read66 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read67 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read68 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read69 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read70 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read71 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read72 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read73 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read74 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read75 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read76 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read77 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read78 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read79 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read80 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read81 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read82 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read83 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read84 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read85 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read86 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read87 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read88 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read89 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read90 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read91 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read92 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read93 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read94 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read95 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read96 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read97 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read98 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read99 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read100 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read101 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read102 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read103 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read104 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read105 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read106 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read107 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read108 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read109 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read110 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read111 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read112 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read113 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read114 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read115 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read116 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read117 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read118 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read119 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read120 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read121 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read122 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read123 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read124 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read125 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read126 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read127 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read128 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read129 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read130 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read131 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read132 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read133 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read134 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read135 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read136 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read137 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read138 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read139 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read140 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read141 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read142 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read143 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read144 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read145 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read146 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read147 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read148 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read149 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read150 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read151 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read152 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read153 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read154 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read155 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read156 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read157 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read158 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read159 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read160 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read161 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read162 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read163 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read164 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read165 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read166 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read167 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read168 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read169 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read170 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read171 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read172 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read173 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read174 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read175 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read176 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read177 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read178 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read179 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read180 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read181 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read182 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read183 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read184 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read185 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read186 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read187 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read188 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read189 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read190 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read191 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read192 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read193 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read194 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read195 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read196 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read197 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read198 : IN STD_LOGIC_VECTOR (7 downto 0);
    p_read199 : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_32 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_33 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_34 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_35 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_36 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_37 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_38 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_39 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_40 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_41 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_42 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_43 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_44 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_45 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_46 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_47 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_48 : OUT STD_LOGIC_VECTOR (13 downto 0);
    ap_return_49 : OUT STD_LOGIC_VECTOR (13 downto 0) );
end;


architecture behav of myproject_pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config18_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_idle : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld : STD_LOGIC;
    signal grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal res_0_copy_fu_604 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_1_copy_fu_600 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_2_copy_fu_596 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_3_copy_fu_592 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_4_copy_fu_588 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_5_copy_fu_584 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_6_copy_fu_580 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_7_copy_fu_576 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_8_copy_fu_572 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_9_copy_fu_568 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_10_copy_fu_564 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_11_copy_fu_560 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_12_copy_fu_556 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_13_copy_fu_552 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_14_copy_fu_548 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_15_copy_fu_544 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_16_copy_fu_540 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_17_copy_fu_536 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_18_copy_fu_532 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_19_copy_fu_528 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_20_copy_fu_524 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_21_copy_fu_520 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_22_copy_fu_516 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_23_copy_fu_512 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_24_copy_fu_508 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_25_copy_fu_504 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_26_copy_fu_500 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_27_copy_fu_496 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_28_copy_fu_492 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_29_copy_fu_488 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_30_copy_fu_484 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_31_copy_fu_480 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_32_copy_fu_476 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_33_copy_fu_472 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_34_copy_fu_468 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_35_copy_fu_464 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_36_copy_fu_460 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_37_copy_fu_456 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_38_copy_fu_452 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_39_copy_fu_448 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_40_copy_fu_444 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_41_copy_fu_440 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_42_copy_fu_436 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_43_copy_fu_432 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_44_copy_fu_428 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_45_copy_fu_424 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_46_copy_fu_420 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_47_copy_fu_416 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_48_copy_fu_412 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_49_copy_fu_408 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myproject_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_read : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read2 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read3 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read4 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read5 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read6 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read7 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read8 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read9 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read10 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read11 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read12 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read13 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read14 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read15 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read16 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read17 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read18 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read19 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read20 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read21 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read22 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read23 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read24 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read25 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read26 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read27 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read28 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read29 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read30 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read31 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read32 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read33 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read34 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read35 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read36 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read37 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read38 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read39 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read40 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read41 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read42 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read43 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read44 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read45 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read46 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read47 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read48 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read49 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read50 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read51 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read52 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read53 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read54 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read55 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read56 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read57 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read58 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read59 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read60 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read61 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read62 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read63 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read64 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read65 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read66 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read67 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read68 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read69 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read70 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read71 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read72 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read73 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read74 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read75 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read76 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read77 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read78 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read79 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read80 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read81 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read82 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read83 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read84 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read85 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read86 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read87 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read88 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read89 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read90 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read91 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read92 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read93 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read94 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read95 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read96 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read97 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read98 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read99 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read100 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read101 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read102 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read103 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read104 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read105 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read106 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read107 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read108 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read109 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read110 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read111 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read112 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read113 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read114 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read115 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read116 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read117 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read118 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read119 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read120 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read121 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read122 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read123 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read124 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read125 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read126 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read127 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read128 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read129 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read130 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read131 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read132 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read133 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read134 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read135 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read136 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read137 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read138 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read139 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read140 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read141 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read142 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read143 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read144 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read145 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read146 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read147 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read148 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read149 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read150 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read151 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read152 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read153 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read154 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read155 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read156 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read157 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read158 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read159 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read160 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read161 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read162 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read163 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read164 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read165 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read166 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read167 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read168 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read169 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read170 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read171 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read172 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read173 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read174 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read175 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read176 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read177 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read178 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read179 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read180 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read181 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read182 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read183 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read184 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read185 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read186 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read187 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read188 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read189 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read190 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read191 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read192 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read193 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read194 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read195 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read196 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read197 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read198 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_read199 : IN STD_LOGIC_VECTOR (7 downto 0);
        res_0 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_0_ap_vld : OUT STD_LOGIC;
        res_1 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_1_ap_vld : OUT STD_LOGIC;
        res_2 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_2_ap_vld : OUT STD_LOGIC;
        res_3 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_3_ap_vld : OUT STD_LOGIC;
        res_4 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_4_ap_vld : OUT STD_LOGIC;
        res_5 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_5_ap_vld : OUT STD_LOGIC;
        res_6 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_6_ap_vld : OUT STD_LOGIC;
        res_7 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_7_ap_vld : OUT STD_LOGIC;
        res_8 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_8_ap_vld : OUT STD_LOGIC;
        res_9 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_9_ap_vld : OUT STD_LOGIC;
        res_10 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_10_ap_vld : OUT STD_LOGIC;
        res_11 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_11_ap_vld : OUT STD_LOGIC;
        res_12 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_12_ap_vld : OUT STD_LOGIC;
        res_13 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_13_ap_vld : OUT STD_LOGIC;
        res_14 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_14_ap_vld : OUT STD_LOGIC;
        res_15 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_15_ap_vld : OUT STD_LOGIC;
        res_16 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_16_ap_vld : OUT STD_LOGIC;
        res_17 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_17_ap_vld : OUT STD_LOGIC;
        res_18 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_18_ap_vld : OUT STD_LOGIC;
        res_19 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_19_ap_vld : OUT STD_LOGIC;
        res_20 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_20_ap_vld : OUT STD_LOGIC;
        res_21 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_21_ap_vld : OUT STD_LOGIC;
        res_22 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_22_ap_vld : OUT STD_LOGIC;
        res_23 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_23_ap_vld : OUT STD_LOGIC;
        res_24 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_24_ap_vld : OUT STD_LOGIC;
        res_25 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_25_ap_vld : OUT STD_LOGIC;
        res_26 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_26_ap_vld : OUT STD_LOGIC;
        res_27 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_27_ap_vld : OUT STD_LOGIC;
        res_28 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_28_ap_vld : OUT STD_LOGIC;
        res_29 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_29_ap_vld : OUT STD_LOGIC;
        res_30 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_30_ap_vld : OUT STD_LOGIC;
        res_31 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_31_ap_vld : OUT STD_LOGIC;
        res_32 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_32_ap_vld : OUT STD_LOGIC;
        res_33 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_33_ap_vld : OUT STD_LOGIC;
        res_34 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_34_ap_vld : OUT STD_LOGIC;
        res_35 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_35_ap_vld : OUT STD_LOGIC;
        res_36 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_36_ap_vld : OUT STD_LOGIC;
        res_37 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_37_ap_vld : OUT STD_LOGIC;
        res_38 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_38_ap_vld : OUT STD_LOGIC;
        res_39 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_39_ap_vld : OUT STD_LOGIC;
        res_40 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_40_ap_vld : OUT STD_LOGIC;
        res_41 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_41_ap_vld : OUT STD_LOGIC;
        res_42 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_42_ap_vld : OUT STD_LOGIC;
        res_43 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_43_ap_vld : OUT STD_LOGIC;
        res_44 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_44_ap_vld : OUT STD_LOGIC;
        res_45 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_45_ap_vld : OUT STD_LOGIC;
        res_46 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_46_ap_vld : OUT STD_LOGIC;
        res_47 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_47_ap_vld : OUT STD_LOGIC;
        res_48 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_48_ap_vld : OUT STD_LOGIC;
        res_49 : OUT STD_LOGIC_VECTOR (13 downto 0);
        res_49_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808 : component myproject_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start,
        ap_done => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done,
        ap_idle => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_idle,
        ap_ready => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready,
        p_read => p_read,
        p_read1 => p_read1,
        p_read2 => p_read2,
        p_read3 => p_read3,
        p_read4 => p_read4,
        p_read5 => p_read5,
        p_read6 => p_read6,
        p_read7 => p_read7,
        p_read8 => p_read8,
        p_read9 => p_read9,
        p_read10 => p_read10,
        p_read11 => p_read11,
        p_read12 => p_read12,
        p_read13 => p_read13,
        p_read14 => p_read14,
        p_read15 => p_read15,
        p_read16 => p_read16,
        p_read17 => p_read17,
        p_read18 => p_read18,
        p_read19 => p_read19,
        p_read20 => p_read20,
        p_read21 => p_read21,
        p_read22 => p_read22,
        p_read23 => p_read23,
        p_read24 => p_read24,
        p_read25 => p_read25,
        p_read26 => p_read26,
        p_read27 => p_read27,
        p_read28 => p_read28,
        p_read29 => p_read29,
        p_read30 => p_read30,
        p_read31 => p_read31,
        p_read32 => p_read32,
        p_read33 => p_read33,
        p_read34 => p_read34,
        p_read35 => p_read35,
        p_read36 => p_read36,
        p_read37 => p_read37,
        p_read38 => p_read38,
        p_read39 => p_read39,
        p_read40 => p_read40,
        p_read41 => p_read41,
        p_read42 => p_read42,
        p_read43 => p_read43,
        p_read44 => p_read44,
        p_read45 => p_read45,
        p_read46 => p_read46,
        p_read47 => p_read47,
        p_read48 => p_read48,
        p_read49 => p_read49,
        p_read50 => p_read50,
        p_read51 => p_read51,
        p_read52 => p_read52,
        p_read53 => p_read53,
        p_read54 => p_read54,
        p_read55 => p_read55,
        p_read56 => p_read56,
        p_read57 => p_read57,
        p_read58 => p_read58,
        p_read59 => p_read59,
        p_read60 => p_read60,
        p_read61 => p_read61,
        p_read62 => p_read62,
        p_read63 => p_read63,
        p_read64 => p_read64,
        p_read65 => p_read65,
        p_read66 => p_read66,
        p_read67 => p_read67,
        p_read68 => p_read68,
        p_read69 => p_read69,
        p_read70 => p_read70,
        p_read71 => p_read71,
        p_read72 => p_read72,
        p_read73 => p_read73,
        p_read74 => p_read74,
        p_read75 => p_read75,
        p_read76 => p_read76,
        p_read77 => p_read77,
        p_read78 => p_read78,
        p_read79 => p_read79,
        p_read80 => p_read80,
        p_read81 => p_read81,
        p_read82 => p_read82,
        p_read83 => p_read83,
        p_read84 => p_read84,
        p_read85 => p_read85,
        p_read86 => p_read86,
        p_read87 => p_read87,
        p_read88 => p_read88,
        p_read89 => p_read89,
        p_read90 => p_read90,
        p_read91 => p_read91,
        p_read92 => p_read92,
        p_read93 => p_read93,
        p_read94 => p_read94,
        p_read95 => p_read95,
        p_read96 => p_read96,
        p_read97 => p_read97,
        p_read98 => p_read98,
        p_read99 => p_read99,
        p_read100 => p_read100,
        p_read101 => p_read101,
        p_read102 => p_read102,
        p_read103 => p_read103,
        p_read104 => p_read104,
        p_read105 => p_read105,
        p_read106 => p_read106,
        p_read107 => p_read107,
        p_read108 => p_read108,
        p_read109 => p_read109,
        p_read110 => p_read110,
        p_read111 => p_read111,
        p_read112 => p_read112,
        p_read113 => p_read113,
        p_read114 => p_read114,
        p_read115 => p_read115,
        p_read116 => p_read116,
        p_read117 => p_read117,
        p_read118 => p_read118,
        p_read119 => p_read119,
        p_read120 => p_read120,
        p_read121 => p_read121,
        p_read122 => p_read122,
        p_read123 => p_read123,
        p_read124 => p_read124,
        p_read125 => p_read125,
        p_read126 => p_read126,
        p_read127 => p_read127,
        p_read128 => p_read128,
        p_read129 => p_read129,
        p_read130 => p_read130,
        p_read131 => p_read131,
        p_read132 => p_read132,
        p_read133 => p_read133,
        p_read134 => p_read134,
        p_read135 => p_read135,
        p_read136 => p_read136,
        p_read137 => p_read137,
        p_read138 => p_read138,
        p_read139 => p_read139,
        p_read140 => p_read140,
        p_read141 => p_read141,
        p_read142 => p_read142,
        p_read143 => p_read143,
        p_read144 => p_read144,
        p_read145 => p_read145,
        p_read146 => p_read146,
        p_read147 => p_read147,
        p_read148 => p_read148,
        p_read149 => p_read149,
        p_read150 => p_read150,
        p_read151 => p_read151,
        p_read152 => p_read152,
        p_read153 => p_read153,
        p_read154 => p_read154,
        p_read155 => p_read155,
        p_read156 => p_read156,
        p_read157 => p_read157,
        p_read158 => p_read158,
        p_read159 => p_read159,
        p_read160 => p_read160,
        p_read161 => p_read161,
        p_read162 => p_read162,
        p_read163 => p_read163,
        p_read164 => p_read164,
        p_read165 => p_read165,
        p_read166 => p_read166,
        p_read167 => p_read167,
        p_read168 => p_read168,
        p_read169 => p_read169,
        p_read170 => p_read170,
        p_read171 => p_read171,
        p_read172 => p_read172,
        p_read173 => p_read173,
        p_read174 => p_read174,
        p_read175 => p_read175,
        p_read176 => p_read176,
        p_read177 => p_read177,
        p_read178 => p_read178,
        p_read179 => p_read179,
        p_read180 => p_read180,
        p_read181 => p_read181,
        p_read182 => p_read182,
        p_read183 => p_read183,
        p_read184 => p_read184,
        p_read185 => p_read185,
        p_read186 => p_read186,
        p_read187 => p_read187,
        p_read188 => p_read188,
        p_read189 => p_read189,
        p_read190 => p_read190,
        p_read191 => p_read191,
        p_read192 => p_read192,
        p_read193 => p_read193,
        p_read194 => p_read194,
        p_read195 => p_read195,
        p_read196 => p_read196,
        p_read197 => p_read197,
        p_read198 => p_read198,
        p_read199 => p_read199,
        res_0 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0,
        res_0_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld,
        res_1 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1,
        res_1_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld,
        res_2 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2,
        res_2_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld,
        res_3 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3,
        res_3_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld,
        res_4 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4,
        res_4_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld,
        res_5 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5,
        res_5_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld,
        res_6 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6,
        res_6_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld,
        res_7 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7,
        res_7_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld,
        res_8 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8,
        res_8_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld,
        res_9 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9,
        res_9_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld,
        res_10 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10,
        res_10_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld,
        res_11 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11,
        res_11_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld,
        res_12 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12,
        res_12_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld,
        res_13 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13,
        res_13_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld,
        res_14 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14,
        res_14_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld,
        res_15 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15,
        res_15_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld,
        res_16 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16,
        res_16_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld,
        res_17 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17,
        res_17_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld,
        res_18 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18,
        res_18_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld,
        res_19 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19,
        res_19_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld,
        res_20 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20,
        res_20_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld,
        res_21 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21,
        res_21_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld,
        res_22 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22,
        res_22_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld,
        res_23 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23,
        res_23_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld,
        res_24 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24,
        res_24_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld,
        res_25 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25,
        res_25_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld,
        res_26 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26,
        res_26_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld,
        res_27 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27,
        res_27_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld,
        res_28 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28,
        res_28_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld,
        res_29 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29,
        res_29_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld,
        res_30 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30,
        res_30_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld,
        res_31 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31,
        res_31_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld,
        res_32 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32,
        res_32_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld,
        res_33 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33,
        res_33_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld,
        res_34 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34,
        res_34_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld,
        res_35 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35,
        res_35_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld,
        res_36 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36,
        res_36_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld,
        res_37 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37,
        res_37_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld,
        res_38 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38,
        res_38_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld,
        res_39 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39,
        res_39_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld,
        res_40 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40,
        res_40_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld,
        res_41 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41,
        res_41_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld,
        res_42 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42,
        res_42_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld,
        res_43 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43,
        res_43_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld,
        res_44 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44,
        res_44_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld,
        res_45 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45,
        res_45_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld,
        res_46 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46,
        res_46_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld,
        res_47 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47,
        res_47_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld,
        res_48 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48,
        res_48_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld,
        res_49 => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49,
        res_49_ap_vld => grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready = ap_const_logic_1)) then 
                    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_0_copy_fu_604 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_10_copy_fu_564 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_11_copy_fu_560 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_12_copy_fu_556 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_13_copy_fu_552 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_14_copy_fu_548 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_15_copy_fu_544 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_16_copy_fu_540 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_17_copy_fu_536 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_18_copy_fu_532 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_19_copy_fu_528 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_1_copy_fu_600 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_20_copy_fu_524 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_21_copy_fu_520 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_22_copy_fu_516 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_23_copy_fu_512 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_24_copy_fu_508 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_25_copy_fu_504 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_26_copy_fu_500 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_27_copy_fu_496 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_28_copy_fu_492 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_29_copy_fu_488 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_2_copy_fu_596 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_30_copy_fu_484 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_31_copy_fu_480 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_32_copy_fu_476 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_33_copy_fu_472 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_34_copy_fu_468 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_35_copy_fu_464 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_36_copy_fu_460 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_37_copy_fu_456 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_38_copy_fu_452 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_39_copy_fu_448 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_3_copy_fu_592 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_40_copy_fu_444 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_41_copy_fu_440 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_42_copy_fu_436 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_43_copy_fu_432 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_44_copy_fu_428 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_45_copy_fu_424 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_46_copy_fu_420 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_47_copy_fu_416 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_48_copy_fu_412 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_49_copy_fu_408 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_4_copy_fu_588 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_5_copy_fu_584 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_6_copy_fu_580 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_7_copy_fu_576 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_8_copy_fu_572 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                res_9_copy_fu_568 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, ap_done_reg)
    begin
        if (((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done)
    begin
        if ((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= res_0_copy_fu_604;
    ap_return_1 <= res_1_copy_fu_600;
    ap_return_10 <= res_10_copy_fu_564;
    ap_return_11 <= res_11_copy_fu_560;
    ap_return_12 <= res_12_copy_fu_556;
    ap_return_13 <= res_13_copy_fu_552;
    ap_return_14 <= res_14_copy_fu_548;
    ap_return_15 <= res_15_copy_fu_544;
    ap_return_16 <= res_16_copy_fu_540;
    ap_return_17 <= res_17_copy_fu_536;
    ap_return_18 <= res_18_copy_fu_532;
    ap_return_19 <= res_19_copy_fu_528;
    ap_return_2 <= res_2_copy_fu_596;
    ap_return_20 <= res_20_copy_fu_524;
    ap_return_21 <= res_21_copy_fu_520;
    ap_return_22 <= res_22_copy_fu_516;
    ap_return_23 <= res_23_copy_fu_512;
    ap_return_24 <= res_24_copy_fu_508;
    ap_return_25 <= res_25_copy_fu_504;
    ap_return_26 <= res_26_copy_fu_500;
    ap_return_27 <= res_27_copy_fu_496;
    ap_return_28 <= res_28_copy_fu_492;
    ap_return_29 <= res_29_copy_fu_488;
    ap_return_3 <= res_3_copy_fu_592;
    ap_return_30 <= res_30_copy_fu_484;
    ap_return_31 <= res_31_copy_fu_480;
    ap_return_32 <= res_32_copy_fu_476;
    ap_return_33 <= res_33_copy_fu_472;
    ap_return_34 <= res_34_copy_fu_468;
    ap_return_35 <= res_35_copy_fu_464;
    ap_return_36 <= res_36_copy_fu_460;
    ap_return_37 <= res_37_copy_fu_456;
    ap_return_38 <= res_38_copy_fu_452;
    ap_return_39 <= res_39_copy_fu_448;
    ap_return_4 <= res_4_copy_fu_588;
    ap_return_40 <= res_40_copy_fu_444;
    ap_return_41 <= res_41_copy_fu_440;
    ap_return_42 <= res_42_copy_fu_436;
    ap_return_43 <= res_43_copy_fu_432;
    ap_return_44 <= res_44_copy_fu_428;
    ap_return_45 <= res_45_copy_fu_424;
    ap_return_46 <= res_46_copy_fu_420;
    ap_return_47 <= res_47_copy_fu_416;
    ap_return_48 <= res_48_copy_fu_412;
    ap_return_49 <= res_49_copy_fu_408;
    ap_return_5 <= res_5_copy_fu_584;
    ap_return_6 <= res_6_copy_fu_580;
    ap_return_7 <= res_7_copy_fu_576;
    ap_return_8 <= res_8_copy_fu_572;
    ap_return_9 <= res_9_copy_fu_568;
    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg;
end behav;
