// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config18_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        p_read64,
        p_read65,
        p_read66,
        p_read67,
        p_read68,
        p_read69,
        p_read70,
        p_read71,
        p_read72,
        p_read73,
        p_read74,
        p_read75,
        p_read76,
        p_read77,
        p_read78,
        p_read79,
        p_read80,
        p_read81,
        p_read82,
        p_read83,
        p_read84,
        p_read85,
        p_read86,
        p_read87,
        p_read88,
        p_read89,
        p_read90,
        p_read91,
        p_read92,
        p_read93,
        p_read94,
        p_read95,
        p_read96,
        p_read97,
        p_read98,
        p_read99,
        p_read100,
        p_read101,
        p_read102,
        p_read103,
        p_read104,
        p_read105,
        p_read106,
        p_read107,
        p_read108,
        p_read109,
        p_read110,
        p_read111,
        p_read112,
        p_read113,
        p_read114,
        p_read115,
        p_read116,
        p_read117,
        p_read118,
        p_read119,
        p_read120,
        p_read121,
        p_read122,
        p_read123,
        p_read124,
        p_read125,
        p_read126,
        p_read127,
        p_read128,
        p_read129,
        p_read130,
        p_read131,
        p_read132,
        p_read133,
        p_read134,
        p_read135,
        p_read136,
        p_read137,
        p_read138,
        p_read139,
        p_read140,
        p_read141,
        p_read142,
        p_read143,
        p_read144,
        p_read145,
        p_read146,
        p_read147,
        p_read148,
        p_read149,
        p_read150,
        p_read151,
        p_read152,
        p_read153,
        p_read154,
        p_read155,
        p_read156,
        p_read157,
        p_read158,
        p_read159,
        p_read160,
        p_read161,
        p_read162,
        p_read163,
        p_read164,
        p_read165,
        p_read166,
        p_read167,
        p_read168,
        p_read169,
        p_read170,
        p_read171,
        p_read172,
        p_read173,
        p_read174,
        p_read175,
        p_read176,
        p_read177,
        p_read178,
        p_read179,
        p_read180,
        p_read181,
        p_read182,
        p_read183,
        p_read184,
        p_read185,
        p_read186,
        p_read187,
        p_read188,
        p_read189,
        p_read190,
        p_read191,
        p_read192,
        p_read193,
        p_read194,
        p_read195,
        p_read196,
        p_read197,
        p_read198,
        p_read199,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_read;
input  [7:0] p_read1;
input  [7:0] p_read2;
input  [7:0] p_read3;
input  [7:0] p_read4;
input  [7:0] p_read5;
input  [7:0] p_read6;
input  [7:0] p_read7;
input  [7:0] p_read8;
input  [7:0] p_read9;
input  [7:0] p_read10;
input  [7:0] p_read11;
input  [7:0] p_read12;
input  [7:0] p_read13;
input  [7:0] p_read14;
input  [7:0] p_read15;
input  [7:0] p_read16;
input  [7:0] p_read17;
input  [7:0] p_read18;
input  [7:0] p_read19;
input  [7:0] p_read20;
input  [7:0] p_read21;
input  [7:0] p_read22;
input  [7:0] p_read23;
input  [7:0] p_read24;
input  [7:0] p_read25;
input  [7:0] p_read26;
input  [7:0] p_read27;
input  [7:0] p_read28;
input  [7:0] p_read29;
input  [7:0] p_read30;
input  [7:0] p_read31;
input  [7:0] p_read32;
input  [7:0] p_read33;
input  [7:0] p_read34;
input  [7:0] p_read35;
input  [7:0] p_read36;
input  [7:0] p_read37;
input  [7:0] p_read38;
input  [7:0] p_read39;
input  [7:0] p_read40;
input  [7:0] p_read41;
input  [7:0] p_read42;
input  [7:0] p_read43;
input  [7:0] p_read44;
input  [7:0] p_read45;
input  [7:0] p_read46;
input  [7:0] p_read47;
input  [7:0] p_read48;
input  [7:0] p_read49;
input  [7:0] p_read50;
input  [7:0] p_read51;
input  [7:0] p_read52;
input  [7:0] p_read53;
input  [7:0] p_read54;
input  [7:0] p_read55;
input  [7:0] p_read56;
input  [7:0] p_read57;
input  [7:0] p_read58;
input  [7:0] p_read59;
input  [7:0] p_read60;
input  [7:0] p_read61;
input  [7:0] p_read62;
input  [7:0] p_read63;
input  [7:0] p_read64;
input  [7:0] p_read65;
input  [7:0] p_read66;
input  [7:0] p_read67;
input  [7:0] p_read68;
input  [7:0] p_read69;
input  [7:0] p_read70;
input  [7:0] p_read71;
input  [7:0] p_read72;
input  [7:0] p_read73;
input  [7:0] p_read74;
input  [7:0] p_read75;
input  [7:0] p_read76;
input  [7:0] p_read77;
input  [7:0] p_read78;
input  [7:0] p_read79;
input  [7:0] p_read80;
input  [7:0] p_read81;
input  [7:0] p_read82;
input  [7:0] p_read83;
input  [7:0] p_read84;
input  [7:0] p_read85;
input  [7:0] p_read86;
input  [7:0] p_read87;
input  [7:0] p_read88;
input  [7:0] p_read89;
input  [7:0] p_read90;
input  [7:0] p_read91;
input  [7:0] p_read92;
input  [7:0] p_read93;
input  [7:0] p_read94;
input  [7:0] p_read95;
input  [7:0] p_read96;
input  [7:0] p_read97;
input  [7:0] p_read98;
input  [7:0] p_read99;
input  [7:0] p_read100;
input  [7:0] p_read101;
input  [7:0] p_read102;
input  [7:0] p_read103;
input  [7:0] p_read104;
input  [7:0] p_read105;
input  [7:0] p_read106;
input  [7:0] p_read107;
input  [7:0] p_read108;
input  [7:0] p_read109;
input  [7:0] p_read110;
input  [7:0] p_read111;
input  [7:0] p_read112;
input  [7:0] p_read113;
input  [7:0] p_read114;
input  [7:0] p_read115;
input  [7:0] p_read116;
input  [7:0] p_read117;
input  [7:0] p_read118;
input  [7:0] p_read119;
input  [7:0] p_read120;
input  [7:0] p_read121;
input  [7:0] p_read122;
input  [7:0] p_read123;
input  [7:0] p_read124;
input  [7:0] p_read125;
input  [7:0] p_read126;
input  [7:0] p_read127;
input  [7:0] p_read128;
input  [7:0] p_read129;
input  [7:0] p_read130;
input  [7:0] p_read131;
input  [7:0] p_read132;
input  [7:0] p_read133;
input  [7:0] p_read134;
input  [7:0] p_read135;
input  [7:0] p_read136;
input  [7:0] p_read137;
input  [7:0] p_read138;
input  [7:0] p_read139;
input  [7:0] p_read140;
input  [7:0] p_read141;
input  [7:0] p_read142;
input  [7:0] p_read143;
input  [7:0] p_read144;
input  [7:0] p_read145;
input  [7:0] p_read146;
input  [7:0] p_read147;
input  [7:0] p_read148;
input  [7:0] p_read149;
input  [7:0] p_read150;
input  [7:0] p_read151;
input  [7:0] p_read152;
input  [7:0] p_read153;
input  [7:0] p_read154;
input  [7:0] p_read155;
input  [7:0] p_read156;
input  [7:0] p_read157;
input  [7:0] p_read158;
input  [7:0] p_read159;
input  [7:0] p_read160;
input  [7:0] p_read161;
input  [7:0] p_read162;
input  [7:0] p_read163;
input  [7:0] p_read164;
input  [7:0] p_read165;
input  [7:0] p_read166;
input  [7:0] p_read167;
input  [7:0] p_read168;
input  [7:0] p_read169;
input  [7:0] p_read170;
input  [7:0] p_read171;
input  [7:0] p_read172;
input  [7:0] p_read173;
input  [7:0] p_read174;
input  [7:0] p_read175;
input  [7:0] p_read176;
input  [7:0] p_read177;
input  [7:0] p_read178;
input  [7:0] p_read179;
input  [7:0] p_read180;
input  [7:0] p_read181;
input  [7:0] p_read182;
input  [7:0] p_read183;
input  [7:0] p_read184;
input  [7:0] p_read185;
input  [7:0] p_read186;
input  [7:0] p_read187;
input  [7:0] p_read188;
input  [7:0] p_read189;
input  [7:0] p_read190;
input  [7:0] p_read191;
input  [7:0] p_read192;
input  [7:0] p_read193;
input  [7:0] p_read194;
input  [7:0] p_read195;
input  [7:0] p_read196;
input  [7:0] p_read197;
input  [7:0] p_read198;
input  [7:0] p_read199;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
output  [13:0] ap_return_8;
output  [13:0] ap_return_9;
output  [13:0] ap_return_10;
output  [13:0] ap_return_11;
output  [13:0] ap_return_12;
output  [13:0] ap_return_13;
output  [13:0] ap_return_14;
output  [13:0] ap_return_15;
output  [13:0] ap_return_16;
output  [13:0] ap_return_17;
output  [13:0] ap_return_18;
output  [13:0] ap_return_19;
output  [13:0] ap_return_20;
output  [13:0] ap_return_21;
output  [13:0] ap_return_22;
output  [13:0] ap_return_23;
output  [13:0] ap_return_24;
output  [13:0] ap_return_25;
output  [13:0] ap_return_26;
output  [13:0] ap_return_27;
output  [13:0] ap_return_28;
output  [13:0] ap_return_29;
output  [13:0] ap_return_30;
output  [13:0] ap_return_31;
output  [13:0] ap_return_32;
output  [13:0] ap_return_33;
output  [13:0] ap_return_34;
output  [13:0] ap_return_35;
output  [13:0] ap_return_36;
output  [13:0] ap_return_37;
output  [13:0] ap_return_38;
output  [13:0] ap_return_39;
output  [13:0] ap_return_40;
output  [13:0] ap_return_41;
output  [13:0] ap_return_42;
output  [13:0] ap_return_43;
output  [13:0] ap_return_44;
output  [13:0] ap_return_45;
output  [13:0] ap_return_46;
output  [13:0] ap_return_47;
output  [13:0] ap_return_48;
output  [13:0] ap_return_49;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_idle;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld;
wire   [13:0] grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49;
wire    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld;
reg    grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [13:0] res_0_copy_fu_604;
reg   [13:0] res_1_copy_fu_600;
reg   [13:0] res_2_copy_fu_596;
reg   [13:0] res_3_copy_fu_592;
reg   [13:0] res_4_copy_fu_588;
reg   [13:0] res_5_copy_fu_584;
reg   [13:0] res_6_copy_fu_580;
reg   [13:0] res_7_copy_fu_576;
reg   [13:0] res_8_copy_fu_572;
reg   [13:0] res_9_copy_fu_568;
reg   [13:0] res_10_copy_fu_564;
reg   [13:0] res_11_copy_fu_560;
reg   [13:0] res_12_copy_fu_556;
reg   [13:0] res_13_copy_fu_552;
reg   [13:0] res_14_copy_fu_548;
reg   [13:0] res_15_copy_fu_544;
reg   [13:0] res_16_copy_fu_540;
reg   [13:0] res_17_copy_fu_536;
reg   [13:0] res_18_copy_fu_532;
reg   [13:0] res_19_copy_fu_528;
reg   [13:0] res_20_copy_fu_524;
reg   [13:0] res_21_copy_fu_520;
reg   [13:0] res_22_copy_fu_516;
reg   [13:0] res_23_copy_fu_512;
reg   [13:0] res_24_copy_fu_508;
reg   [13:0] res_25_copy_fu_504;
reg   [13:0] res_26_copy_fu_500;
reg   [13:0] res_27_copy_fu_496;
reg   [13:0] res_28_copy_fu_492;
reg   [13:0] res_29_copy_fu_488;
reg   [13:0] res_30_copy_fu_484;
reg   [13:0] res_31_copy_fu_480;
reg   [13:0] res_32_copy_fu_476;
reg   [13:0] res_33_copy_fu_472;
reg   [13:0] res_34_copy_fu_468;
reg   [13:0] res_35_copy_fu_464;
reg   [13:0] res_36_copy_fu_460;
reg   [13:0] res_37_copy_fu_456;
reg   [13:0] res_38_copy_fu_452;
reg   [13:0] res_39_copy_fu_448;
reg   [13:0] res_40_copy_fu_444;
reg   [13:0] res_41_copy_fu_440;
reg   [13:0] res_42_copy_fu_436;
reg   [13:0] res_43_copy_fu_432;
reg   [13:0] res_44_copy_fu_428;
reg   [13:0] res_45_copy_fu_424;
reg   [13:0] res_46_copy_fu_420;
reg   [13:0] res_47_copy_fu_416;
reg   [13:0] res_48_copy_fu_412;
reg   [13:0] res_49_copy_fu_408;
wire    ap_CS_fsm_state4;
reg    ap_block_state1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg = 1'b0;
end

myproject_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start),
    .ap_done(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done),
    .ap_idle(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_idle),
    .ap_ready(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready),
    .p_read(p_read),
    .p_read1(p_read1),
    .p_read2(p_read2),
    .p_read3(p_read3),
    .p_read4(p_read4),
    .p_read5(p_read5),
    .p_read6(p_read6),
    .p_read7(p_read7),
    .p_read8(p_read8),
    .p_read9(p_read9),
    .p_read10(p_read10),
    .p_read11(p_read11),
    .p_read12(p_read12),
    .p_read13(p_read13),
    .p_read14(p_read14),
    .p_read15(p_read15),
    .p_read16(p_read16),
    .p_read17(p_read17),
    .p_read18(p_read18),
    .p_read19(p_read19),
    .p_read20(p_read20),
    .p_read21(p_read21),
    .p_read22(p_read22),
    .p_read23(p_read23),
    .p_read24(p_read24),
    .p_read25(p_read25),
    .p_read26(p_read26),
    .p_read27(p_read27),
    .p_read28(p_read28),
    .p_read29(p_read29),
    .p_read30(p_read30),
    .p_read31(p_read31),
    .p_read32(p_read32),
    .p_read33(p_read33),
    .p_read34(p_read34),
    .p_read35(p_read35),
    .p_read36(p_read36),
    .p_read37(p_read37),
    .p_read38(p_read38),
    .p_read39(p_read39),
    .p_read40(p_read40),
    .p_read41(p_read41),
    .p_read42(p_read42),
    .p_read43(p_read43),
    .p_read44(p_read44),
    .p_read45(p_read45),
    .p_read46(p_read46),
    .p_read47(p_read47),
    .p_read48(p_read48),
    .p_read49(p_read49),
    .p_read50(p_read50),
    .p_read51(p_read51),
    .p_read52(p_read52),
    .p_read53(p_read53),
    .p_read54(p_read54),
    .p_read55(p_read55),
    .p_read56(p_read56),
    .p_read57(p_read57),
    .p_read58(p_read58),
    .p_read59(p_read59),
    .p_read60(p_read60),
    .p_read61(p_read61),
    .p_read62(p_read62),
    .p_read63(p_read63),
    .p_read64(p_read64),
    .p_read65(p_read65),
    .p_read66(p_read66),
    .p_read67(p_read67),
    .p_read68(p_read68),
    .p_read69(p_read69),
    .p_read70(p_read70),
    .p_read71(p_read71),
    .p_read72(p_read72),
    .p_read73(p_read73),
    .p_read74(p_read74),
    .p_read75(p_read75),
    .p_read76(p_read76),
    .p_read77(p_read77),
    .p_read78(p_read78),
    .p_read79(p_read79),
    .p_read80(p_read80),
    .p_read81(p_read81),
    .p_read82(p_read82),
    .p_read83(p_read83),
    .p_read84(p_read84),
    .p_read85(p_read85),
    .p_read86(p_read86),
    .p_read87(p_read87),
    .p_read88(p_read88),
    .p_read89(p_read89),
    .p_read90(p_read90),
    .p_read91(p_read91),
    .p_read92(p_read92),
    .p_read93(p_read93),
    .p_read94(p_read94),
    .p_read95(p_read95),
    .p_read96(p_read96),
    .p_read97(p_read97),
    .p_read98(p_read98),
    .p_read99(p_read99),
    .p_read100(p_read100),
    .p_read101(p_read101),
    .p_read102(p_read102),
    .p_read103(p_read103),
    .p_read104(p_read104),
    .p_read105(p_read105),
    .p_read106(p_read106),
    .p_read107(p_read107),
    .p_read108(p_read108),
    .p_read109(p_read109),
    .p_read110(p_read110),
    .p_read111(p_read111),
    .p_read112(p_read112),
    .p_read113(p_read113),
    .p_read114(p_read114),
    .p_read115(p_read115),
    .p_read116(p_read116),
    .p_read117(p_read117),
    .p_read118(p_read118),
    .p_read119(p_read119),
    .p_read120(p_read120),
    .p_read121(p_read121),
    .p_read122(p_read122),
    .p_read123(p_read123),
    .p_read124(p_read124),
    .p_read125(p_read125),
    .p_read126(p_read126),
    .p_read127(p_read127),
    .p_read128(p_read128),
    .p_read129(p_read129),
    .p_read130(p_read130),
    .p_read131(p_read131),
    .p_read132(p_read132),
    .p_read133(p_read133),
    .p_read134(p_read134),
    .p_read135(p_read135),
    .p_read136(p_read136),
    .p_read137(p_read137),
    .p_read138(p_read138),
    .p_read139(p_read139),
    .p_read140(p_read140),
    .p_read141(p_read141),
    .p_read142(p_read142),
    .p_read143(p_read143),
    .p_read144(p_read144),
    .p_read145(p_read145),
    .p_read146(p_read146),
    .p_read147(p_read147),
    .p_read148(p_read148),
    .p_read149(p_read149),
    .p_read150(p_read150),
    .p_read151(p_read151),
    .p_read152(p_read152),
    .p_read153(p_read153),
    .p_read154(p_read154),
    .p_read155(p_read155),
    .p_read156(p_read156),
    .p_read157(p_read157),
    .p_read158(p_read158),
    .p_read159(p_read159),
    .p_read160(p_read160),
    .p_read161(p_read161),
    .p_read162(p_read162),
    .p_read163(p_read163),
    .p_read164(p_read164),
    .p_read165(p_read165),
    .p_read166(p_read166),
    .p_read167(p_read167),
    .p_read168(p_read168),
    .p_read169(p_read169),
    .p_read170(p_read170),
    .p_read171(p_read171),
    .p_read172(p_read172),
    .p_read173(p_read173),
    .p_read174(p_read174),
    .p_read175(p_read175),
    .p_read176(p_read176),
    .p_read177(p_read177),
    .p_read178(p_read178),
    .p_read179(p_read179),
    .p_read180(p_read180),
    .p_read181(p_read181),
    .p_read182(p_read182),
    .p_read183(p_read183),
    .p_read184(p_read184),
    .p_read185(p_read185),
    .p_read186(p_read186),
    .p_read187(p_read187),
    .p_read188(p_read188),
    .p_read189(p_read189),
    .p_read190(p_read190),
    .p_read191(p_read191),
    .p_read192(p_read192),
    .p_read193(p_read193),
    .p_read194(p_read194),
    .p_read195(p_read195),
    .p_read196(p_read196),
    .p_read197(p_read197),
    .p_read198(p_read198),
    .p_read199(p_read199),
    .res_0(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0),
    .res_0_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld),
    .res_1(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1),
    .res_1_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld),
    .res_2(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2),
    .res_2_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld),
    .res_3(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3),
    .res_3_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld),
    .res_4(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4),
    .res_4_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld),
    .res_5(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5),
    .res_5_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld),
    .res_6(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6),
    .res_6_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld),
    .res_7(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7),
    .res_7_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld),
    .res_8(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8),
    .res_8_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld),
    .res_9(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9),
    .res_9_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld),
    .res_10(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10),
    .res_10_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld),
    .res_11(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11),
    .res_11_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld),
    .res_12(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12),
    .res_12_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld),
    .res_13(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13),
    .res_13_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld),
    .res_14(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14),
    .res_14_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld),
    .res_15(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15),
    .res_15_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld),
    .res_16(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16),
    .res_16_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld),
    .res_17(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17),
    .res_17_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld),
    .res_18(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18),
    .res_18_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld),
    .res_19(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19),
    .res_19_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld),
    .res_20(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20),
    .res_20_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld),
    .res_21(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21),
    .res_21_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld),
    .res_22(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22),
    .res_22_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld),
    .res_23(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23),
    .res_23_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld),
    .res_24(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24),
    .res_24_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld),
    .res_25(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25),
    .res_25_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld),
    .res_26(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26),
    .res_26_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld),
    .res_27(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27),
    .res_27_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld),
    .res_28(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28),
    .res_28_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld),
    .res_29(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29),
    .res_29_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld),
    .res_30(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30),
    .res_30_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld),
    .res_31(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31),
    .res_31_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld),
    .res_32(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32),
    .res_32_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld),
    .res_33(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33),
    .res_33_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld),
    .res_34(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34),
    .res_34_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld),
    .res_35(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35),
    .res_35_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld),
    .res_36(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36),
    .res_36_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld),
    .res_37(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37),
    .res_37_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld),
    .res_38(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38),
    .res_38_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld),
    .res_39(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39),
    .res_39_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld),
    .res_40(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40),
    .res_40_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld),
    .res_41(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41),
    .res_41_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld),
    .res_42(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42),
    .res_42_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld),
    .res_43(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43),
    .res_43_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld),
    .res_44(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44),
    .res_44_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld),
    .res_45(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45),
    .res_45_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld),
    .res_46(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46),
    .res_46_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld),
    .res_47(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47),
    .res_47_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld),
    .res_48(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48),
    .res_48_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld),
    .res_49(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49),
    .res_49_ap_vld(grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state4)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= 1'b1;
        end else if ((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_ready == 1'b1)) begin
            grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_0_copy_fu_604 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_10_copy_fu_564 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_10;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_11_copy_fu_560 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_11;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_12_copy_fu_556 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_12;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_13_copy_fu_552 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_13;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_14_copy_fu_548 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_14;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_15_copy_fu_544 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_15;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_16_copy_fu_540 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_16;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_17_copy_fu_536 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_17;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_18_copy_fu_532 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_18;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_19_copy_fu_528 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_19;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_1_copy_fu_600 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_20_copy_fu_524 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_20;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_21_copy_fu_520 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_21;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_22_copy_fu_516 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_22;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_23_copy_fu_512 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_23;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_24_copy_fu_508 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_24;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_25_copy_fu_504 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_25;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_26_copy_fu_500 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_26;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_27_copy_fu_496 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_27;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_28_copy_fu_492 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_28;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_29_copy_fu_488 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_29;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_2_copy_fu_596 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_30_copy_fu_484 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_30;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_31_copy_fu_480 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_31;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_32_copy_fu_476 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_32;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_33_copy_fu_472 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_33;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_34_copy_fu_468 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_34;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_35_copy_fu_464 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_35;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_36_copy_fu_460 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_36;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_37_copy_fu_456 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_37;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_38_copy_fu_452 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_38;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_39_copy_fu_448 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_39;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_3_copy_fu_592 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_40_copy_fu_444 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_40;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_41_copy_fu_440 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_41;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_42_copy_fu_436 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_42;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_43_copy_fu_432 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_43;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_44_copy_fu_428 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_44;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_45_copy_fu_424 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_45;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_46_copy_fu_420 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_46;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_47_copy_fu_416 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_47;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_48_copy_fu_412 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_48;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_49_copy_fu_408 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_49;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_4_copy_fu_588 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_4;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_5_copy_fu_584 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_5;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_6_copy_fu_580 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_7_copy_fu_576 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_7;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_8_copy_fu_572 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_8;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        res_9_copy_fu_568 <= grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_res_9;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_return_0 = res_0_copy_fu_604;

assign ap_return_1 = res_1_copy_fu_600;

assign ap_return_10 = res_10_copy_fu_564;

assign ap_return_11 = res_11_copy_fu_560;

assign ap_return_12 = res_12_copy_fu_556;

assign ap_return_13 = res_13_copy_fu_552;

assign ap_return_14 = res_14_copy_fu_548;

assign ap_return_15 = res_15_copy_fu_544;

assign ap_return_16 = res_16_copy_fu_540;

assign ap_return_17 = res_17_copy_fu_536;

assign ap_return_18 = res_18_copy_fu_532;

assign ap_return_19 = res_19_copy_fu_528;

assign ap_return_2 = res_2_copy_fu_596;

assign ap_return_20 = res_20_copy_fu_524;

assign ap_return_21 = res_21_copy_fu_520;

assign ap_return_22 = res_22_copy_fu_516;

assign ap_return_23 = res_23_copy_fu_512;

assign ap_return_24 = res_24_copy_fu_508;

assign ap_return_25 = res_25_copy_fu_504;

assign ap_return_26 = res_26_copy_fu_500;

assign ap_return_27 = res_27_copy_fu_496;

assign ap_return_28 = res_28_copy_fu_492;

assign ap_return_29 = res_29_copy_fu_488;

assign ap_return_3 = res_3_copy_fu_592;

assign ap_return_30 = res_30_copy_fu_484;

assign ap_return_31 = res_31_copy_fu_480;

assign ap_return_32 = res_32_copy_fu_476;

assign ap_return_33 = res_33_copy_fu_472;

assign ap_return_34 = res_34_copy_fu_468;

assign ap_return_35 = res_35_copy_fu_464;

assign ap_return_36 = res_36_copy_fu_460;

assign ap_return_37 = res_37_copy_fu_456;

assign ap_return_38 = res_38_copy_fu_452;

assign ap_return_39 = res_39_copy_fu_448;

assign ap_return_4 = res_4_copy_fu_588;

assign ap_return_40 = res_40_copy_fu_444;

assign ap_return_41 = res_41_copy_fu_440;

assign ap_return_42 = res_42_copy_fu_436;

assign ap_return_43 = res_43_copy_fu_432;

assign ap_return_44 = res_44_copy_fu_428;

assign ap_return_45 = res_45_copy_fu_424;

assign ap_return_46 = res_46_copy_fu_420;

assign ap_return_47 = res_47_copy_fu_416;

assign ap_return_48 = res_48_copy_fu_412;

assign ap_return_49 = res_49_copy_fu_408;

assign ap_return_5 = res_5_copy_fu_584;

assign ap_return_6 = res_6_copy_fu_580;

assign ap_return_7 = res_7_copy_fu_576;

assign ap_return_8 = res_8_copy_fu_572;

assign ap_return_9 = res_9_copy_fu_568;

assign grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start = grp_conv_1d_latency_cl_ap_fixed_9_4_0_0_0_ap_fixed_16_6_5_3_0_config18_s_fu_1808_ap_start_reg;

endmodule //myproject_pointwise_conv_1d_cl_ap_fixed_ap_fixed_16_6_5_3_0_config18_s
